version: '3'
services:
 db:
   image: mysql:5.7
   volumes:
     - ./db/mysql:/var/lib/mysql
     - ./db/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: somewordpress
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress
 wordpress:
   depends_on:
     - db
   image: wordpress:latest
   ports:
     - "8000:80"
   restart: always
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
   volumes:
     - ./wordpress/html:/var/www/html
     - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
 phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   restart: always
   depends_on:
     - db
   ports:
     - 8080:80
volumes:
  db_data: